config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  patch '/task/:id/mark-as-done' => "tasks#mark_as_done", as: :mark_as_done
  patch '/task/:id/mark-as-to-do' => "tasks#mark_as_undone", as: :mark_as_undone
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @task.status = "done"
    @task.save
    redirect_to task_path(@task.id)
  end

  def mark_as_undone
    @task = Task.find(params[:id])
    @task.status = "to do"
    @task.save
    redirect_to task_path(@task.id)
  end

  private

   def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:content, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :status %>
  <%= f.select :status, ['done', 'to do']%>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1 class="text-center">Here is the list of your tasks</h1>
<% @tasks.each do |task| %>
<h2><%= link_to task.content, task_path(task) %></h2>
<p><%= task.status %></p>
<%= link_to "Show this task", task_path(task)%>
<%= link_to "Mark this task as done", mark_as_done_path(task), method: :patch%>
<%= link_to "Mark this task as to-do", mark_as_undone_path(task), method: :patch%>
<% end %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.label :status %>
  <%= f.select :status, ['done', 'to do']%>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.content %></h2>
<p><%= @task.status %></p>
<%= link_to "Delete this task", task_path(@task), method: :delete %>
<%= link_to "Back to index", tasks_path %>